/**
 * N6 - Version (Fase G3)
 * Auto-generated by tools/build.sh. Do not edit manually.
 */
export const N6_VERSION = 'v2026.10.06-f99262a';
export const N6_BUILD_HASH = 'f99262a';
export const N6_BUILD_DATE = '2026.10.06';
export default N6_VERSION;
